export const WS_EVENTS = {
  CONNECT: 'connect',
  DISCONNECT: 'disconnect',
  ERROR: 'error',

  AUTHENTICATED: 'AUTHENTICATED',

  CHAT_MESSAGE: 'CHAT_MESSAGE',
  CHAT_TYPING: 'CHAT_TYPING',
  CHAT_READ: 'CHAT_READ',

  NOTIFICATION: 'NOTIFICATION',

  JOB_UPDATED: 'JOB_UPDATED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',

  SYSTEM_ALERT: 'SYSTEM_ALERT',

  ONLINE_USERS: 'ONLINE_USERS',

  PING: 'PING',
  PONG: 'PONG',
} as const;

export const WS_STATUS = {
  DISCONNECTED: 'DISCONNECTED',
  CONNECTING: 'CONNECTING',
  CONNECTED: 'CONNECTED',
  RECONNECTING: 'RECONNECTING',
  AUTHENTICATING: 'AUTHENTICATING',
} as const;

export const HEARTBEAT_INTERVAL = 30000;

export const HEARTBEAT_TIMEOUT = 10000;

export const MAX_RECONNECT_ATTEMPTS = 10;

export const BASE_RECONNECT_DELAY = 1000;