import {
  Home,
  House,
  User,
  Users,
  Bell,
  Search,
  Settings,
  Menu,
  Plus,
  X,
  ChevronLeft,
  ChevronRight,
  ArrowLeft,
  ArrowRight,
  Eye,
  EyeOff,
  Mail,
  Lock,
  Phone,
  Camera,
  Image,
  Upload,
  Download,
  Trash2,
  Pencil,
  Check,
  CircleAlert,
  Info,
  LoaderCircle,
  Calendar,
  Clock,
  FileText,
  Folder,
  Heart,
  Star,
  Building2,
  Briefcase,
  CreditCard,
  Shield,
  LogOut,
} from 'lucide-react-native';

export const icons = {
  home: Home,
  house: House,
  user: User,
  users: Users,
  bell: Bell,
  search: Search,
  settings: Settings,
  menu: Menu,
  plus: Plus,
  close: X,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  eye: Eye,
  eyeOff: EyeOff,
  mail: Mail,
  lock: Lock,
  phone: Phone,
  camera: Camera,
  image: Image,
  upload: Upload,
  download: Download,
  trash: Trash2,
  edit: Pencil,
  check: Check,
  alert: CircleAlert,
  info: Info,
  loader: LoaderCircle,
  calendar: Calendar,
  clock: Clock,
  file: FileText,
  folder: Folder,
  heart: Heart,
  star: Star,
  company: Building2,
  job: Briefcase,
  payment: CreditCard,
  security: Shield,
  logout: LogOut,
} as const;